development:
  adapter: postgresql
  encoding: unicode
  database: meteor_development
  pool: 5
  username: percydai
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: meteor_test
  pool: 5
  username: percydai
  password:
  timeout: 5000